# -*- coding: utf-8 -*-
"""python101.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AdJamfrSLGP33LyIYTkGq12TYkuyDTvY

# Intro to Python

## 0: Note on syntax
If you're completely new to python it may be helpful to pause here and cover a few basic syntactical rules. In programming, **syntax** is the rules of the language and it varies depending what language you're using (just like human languages).

* Every line of code in python is a statement and there are different kinds of statements. For example, a **conditional statement** is one kind of statement; an **assignment** is another kind of statement.
* Each statement in python should be written on a new line.
* There is no semi-colon at the end of a line of python code. In some languages a semi-colon may be used to delimit statements, but in python it is the new lines and indentations which are important.
* Code blocks are groups of statements that are executed as a unit.
* A conditional statement is a code block, since the use of conditional statements is a way of grouping lines of code together into a block.

## 1: Print
The `print()` function prints the specified message to the screen, or other standard output device.

The most basic usage of a print function takes a string as input.
"""

print("Hello, world!")

"""It can also work with numbers (integers, floats, *etc.*)."""

print("3")
print("2.5")

"""The print function can take more than one object, and you can define a custom separator to separate the objects."""

print("Hello", "how are you?")
print("Hello", "how are you?", sep="--")

"""## 2: Variables.
Python variables are the reserved memory locations used to store values within a Python program. This means that when you create a variable, some space in memory gets reserved. Based on the data type of a variable, Python interpreter allocates memory and decides what can be stored in the reserved memory. Therefore, by assigning different data types to Python variables, you can store integers, decimals, or characters in these variables.

### 2-1: Declare Python variables.
"""

counter = 100           # Creates an integer variable
miles   = 1600.0        # Creates a floating point variable
name    = "Squidward"   # Creates a string variable

print(counter)
print(miles)
print(name)

"""### 2-2: Delete Python variables.
You can delete one or multiple objects by using the del statement. The syntax of the del statement is:
```
del var
del var_a var_b
```


"""

counter = 100
print(counter)

del counter
print(counter) # A NameError is expected to show up because of the prior del statement

"""### 2-3: Multiple assignment
Python allows to initialize more than one variables in a single statement.
"""

a = b = c = 10                     # Intialize more than one variables to the same value in a single statement
print(a, b, c)

a, b, c = 1, 2.5, "Patrick Star"   # Assign mutiple objects to multiple variables
print(a, b, c)

"""## 3: The control flow.

### 3-1: The if statement.
Python provides `if...elif...else` statements as part of decision making.
"""

score = 80
result = ""

if score < 50:
  result = "Failed"
elif score > 85:
  result = "Passed with distinction"
else:
  result = "Passed"

print(result)

"""###3-2: The match statement.
Python supports `match-case` statement, which can be also used as a part of decision making.
"""

def checkVowel(n):
  match n:
    case 'a': return "vowel alphabet"
    case 'e': return "vowel alphabet"
    case 'i': return "vowel alphabet"
    case 'o': return "vowel alphabet"
    case 'u': return "vowel alphabet"
    case _: return "simple alphabet"

print("letter a is a " + checkVowel('a'))
print("letter m is a " + checkVowel('m'))
print("letter o is a " + checkVowel('o'))

"""## 4: Loops or iteration statements.
Most of the processes require a series of instructions to be repeated executed. In programming terminology, it is called a loop.

If the control goes back unconditionally, it forms an infinite loop which is not desired as the rest of the code would *never* get executed.

In a conditional loop, the repeated iteration of block of statements goes on till a certain condition is met. Python supports a number of loops like *for* loop and *while* loop, as demonstrated in the following blocks.

### 4-1: The for loop.
"""

basket = ["apple", "peach", "watermelon"]
for x in basket:
  print(x)

"""### 4-2: The while loop."""

iter = 1
while iter < 6:
  print(iter)
  iter += 1

"""### 4-3: The break statement.

The *break* statement terminates the current loop and resumes execution at the next statement, and the most common use case is when some external condition is triggered requiring a hasty exit from a loop.

The break statement can be used in both for and while loops.

If you are using nested loops, the break statement stops the execution of the innermost loop and start executing the next line of the code after the block.
"""

for letter in "Python":
  if letter == 'h':
    break
  print("Current letter: ", letter)

var = 10
while var > 0:
  print("Value of var: ", var)
  var = var - 1
  if var == 5:
    break

print("Good bye!")

"""### 4-4: The continue statement.

The *continue* statement in Python returns the control to the beginning of the current loop. When encountered, the loop starts next iteration without executing the remaining statements in the current iteration.

The continue statement can be used in both for and while loops.
"""

for letter in "Python":
  if letter == "h":
    print("This is the continue block")
    continue
  print("Current letter: ", letter)
print("See you!")

# checking prime factors
num = 60
print("Checking prime factors for: ", num)

d = 2
while num > 1:
  if num % d == 0:
    print(d)
    num = num / d
    continue
  d = d + 1

"""### 4-5: The pass statement.

The *pass* statement is used when a statement is required syntactically but you do not want any command or code to execute.

The Python pass statement is a null operation, nothing happens when it executes. It can also be used as a placeholder (*i.e.*, in stubs) for your code where the details  have not yet been implemented.

"""

for letter in "Python":
  if letter == "h":
    pass
    print("This is the pass block")
  print("Current letter: ", letter)
print("Good bye!")

"""One can use ellipses `...` as a pass alternative:"""

def func1():
  ...           # alternative to pass

func1()         # does nothing if called

"""## 5: Functions.
A Python function is a block of organized, reusable code that is used to perform a single, related action. Functions provide better modularity for your application and a high degree of code reusing.

A top-to-down approach towards building the processing logic involves defining blocks of independent reusable functions. A Python function may get invoked by any other function by passing required arguments. The called function returns its result back to the calling environment.

### 5-1: Python built-in functions.
Python's standard library includes a variety of built-in functions. The frequently used ones are `print()`, `int()`, `len()`, `sum()`, etc. These functions are always available, as they are loaded into computer's memory as soon as you start the Python interpreter.
"""

nums = [1, 2, 3, 4, 5]

print(len(nums))
print(sum(nums))

"""### 5-2: Define a function in Python.
In addition to the built-in functions and functions in the built-in modules, you can also create your own functions. These functions are called user-defined functions.

Here are some simple rules to define a function in Python.
*   Function blocks begin with the keyword `def` followed by the function name and parentheses.
*   Any input arguments should be placed within these parentheses. You can also define parameters inside these parentheses.
*   The code block within every function starts with a colon (`:`) and is indented
*   The statement `return [expression]` exits a function, optionally passing back an expression to the caller. A `return` statement with no arguments is the same as `return None`.

Basic function syntax:
```
def my_function(params):
  '''
  function briefs
  '''
  function_body
  return [expression]
```
Note that parameters / arguments have a positional behavior and you need to inform them in the same order that they were defined.

Once the function is defined, you can execute it by calling it from another function or directly from the Python prompt (CLI).
"""

def print_list(my_list):
  '''
  This string prints all the list elements passed to it.
  '''
  for x in my_list:
    print(x)
  return

cake_recipe = ["flour", 2, "butter", 1, "sugar", 0.5, "egg", 3]
print_list(cake_recipe)

# function with return value with type hints
def add(x, y):
  sum = x + y
  return sum

print(add(20, 30))

"""### 5-3. Python scope.
A variable created inside a functions belongs to the *local* scope of that function, and can only be used inside that function.

"""

def my_func():
  local_val = 5
  print(local_val)
  return

my_func()

print(local_val)    # You're expected to see a NameError complaining that 'local_val' isn't defined.

"""As explained in the example above, the variable `local_val` is not available outside the function, but it is available for any function inside the function:"""

def my_func():
  local_val = 10
  def my_inner_func():
    print(local_val)
  my_inner_func()
  return

my_func()

"""## 6: Basic Python import.
Python code is organized into both modules and packages. Using the import keyword can make code in one module available in another, so that imports are important for structuring your code effectively. This will also allow you to use modules and packages in your code and keep the projects maintainable.

Import the code in the *math* module and make it available to use.
Note: math is part of Python's standard library, which means that it's always available to import when you're running Python
"""

import math

"""Access the `pi` variable within the math module."""

print(math.pi)

"""In addition to being a module, math acts as a *namespace* the keepsall the attributes of the module together. Namespaces are useful for keeping your code readable and organized.

You can list the contents of a namespace with `dir()`
"""

dir(math)

"""The following code imports only the `pi` variable from the math module:"""

from math import pi
# this places pi in the global namespace and not within a math namespace
print(pi)

"""You can also rename modules and attributes when they're imported:

"""

import math as m
print(m.pi)

from math import pi as M_PI
print(M_PI)

"""In this course, we'll be frequently using a couple of libraries to perform data processing, analysis, and visualization. They can be imported to your python notebooks or scripts in the following way:"""

'''
NumPy is a Python library used for working with arrays.
It also has functions working in domain of linear algebra, fourier transform, and matrices.
Numpy is usually imported under the np alias.
'''
import numpy as np
'''
You can check the version of the imported NumPy library by inspecting the __version__ attribute.
'''
print(np.__version__)
'''
The array object in NumPy is called ndarray, it provides a lot of supporting functions that
make working with ndarray easily.
'''
fp_nums = [1.3, 3.2, 8.0, 5.7, -0.6]
arr = np.array(fp_nums, dtype = np.float32)

print(arr)
print(type(arr))
print(arr.shape)

'''
Pandas allows us to analyze big data and make hyppthesis based on statistical theories.
Pandas is usually imported under the pd alias.
'''
import pandas as pd
'''
You can check the version of the imported Pandas library by inspecting the __version__ attribute.
'''
print(pd.__version__)
'''
The following example demonstrates how to create a basic Pandas DataFrame from a Python
dictionary object.
'''
my_dataset = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

my_df = pd.DataFrame(my_dataset)
print(my_df)
# locate certain rows
print(my_df.loc[[0, 2]])

'''
Scipy is a scientific computation library that uses NumPy underneath.
Scipy stands for Scientific Python.
This example illustrates the triangulation of a polygon.
'''
from scipy.spatial import Delaunay
import matplotlib.pyplot as plt

points = np.array([
  [2, 4],
  [3, 4],
  [3, 0],
  [2, 2],
  [4, 1]
])

simplices = Delaunay(points).simplices

plt.triplot(points[:, 0], points[:, 1], simplices)
plt.scatter(points[:, 0], points[:, 1], color='r')

plt.show()

"""## 7: Other related materials.
*   Beginner's guide to Python: [link](https://wiki.python.org/moin/BeginnersGuide)
*   The official Python3 tutorial: [link](https://docs.python.org/3/tutorial/index.html)

"""